### PR TITLE
Add dnf bucket

### PR DESCRIPTION
**Pull request by raghavendra-talur**
This patchset adds dnf as a bucket.
Adds the keepcache line if it is not found in dnf.conf.

Signed-off-by: raghavendra talur raghavendra.talur@gmail.com

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
I have used to for a few days now and it seems to be working fine. Can anyone please review this?

**Comment by kianmeng** [comment]
Doesn't seems to work for me with Vagrant and [Fedora 23 Cloud](https://getfedora.org/en/cloud/download/). Let me know if I miss out anything.

Version-Release number of selected component (if applicable):
````
Vagrant: 1.7.4
VirtualBox: 5.0.8 r103449
````

Steps to Reproduce:
````
1. sudo dnf install git ruby-devel vagrant virtualbox-5.0
2. git clone https://github.com/fgrehm/vagrant-cachier.git
3. cd vagrant-cachier
4. curl -sSL https://github.com/fgrehm/vagrant-cachier/pull/158.patch | git am
5. sed -i 's/1.2.1/1.2.2/' lib/vagrant-cachier/version.rb
6. bundle install
7. bundle exec rake build
8. vagrant plugin install pkg/vagrant-cachier-1.2.2.gem
````

````
9. vagrant plugin list
vagrant-cachier (1.2.2)
  - Version Constraint: 1.2.2
vagrant-libvirt (0.0.30, system)
vagrant-lxc (1.1.0, system)
vagrant-vbguest (0.11.0)
vagrant-vbox-snapshot (0.0.9)
````

````
10. mkdir -p /tmp/test
11. cd -p /tmp/test
12. vagrant init fedora/23
13. Edit Vagrantfile

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
  }
 ````

````
14. vagrant up --provider=virtualbox
15. vagrant ssh
16. sudo su -
17. dnf update
````

Expected results:
````
find ~/.vagrant.d/cache/fedora/23/ -maxdepth 1 -type f | wc -l
0 <-- not supposed to be zero.
````

**Comment by fgrehm** [comment]
Sorry but as per GH-143 I'm looking for help to maintain this plugin and for now I'm holding back from bringing in changes to the code =/

If you are interested on maintaining the project and keep things moving please shoot me an email or drop a message on GH-143 so I can arrange things.

Cheers :beers:

**Comment by raghavendra-talur** [comment]
Fixed by #180

**Pull request closed without merging**
