### PR TITLE
Add pip cache bucket

### LINKED ISSUE #80: Support for caching python modules
I'm a bit of a newb when it comes to python packaging so I don't know the details. Like rubygems, pip is used to install packages from remote repositories.

### PR DESCRIPTION
**Pull request by SeMeKh**
Fixes #80. Works around locking issue with pip.

### CODE REVIEW

**Comment by fgrehm** [comment]
Sorry but as per GH-143 I'm looking for help to maintain this plugin and for now I'm holding back from bringing in new features =/

If you are interested on maintaining the project and keep things moving please shoot me an email or drop a message on GH-143 so I can arrange things.

Cheers

**Comment by gotlium** [comment]
Hi. Why you are using ``$HOME/.cache/pip/http`` and ``$HOME/.cache/pip/wheels`` ? 
By default pip using it's own directory ``$HOME/.pip/cache``
Can you add to documentation ``export PIP_DOWNLOAD_CACHE``, or link to pip docs
:smiley: :thumbsup:

> There are also a legacy per-user configuration file which is also respected, these are located at:
> On Unix and Mac OS X the configuration file is: $HOME/.pip/pip.conf
> On Windows the configuration file is: %HOME%\pip\pip.ini

@fgrehm I think we can maintain this plugin :smile:

**Comment by SeMeKh** [comment]
It's not possible to simply use `$HOME/.cache/pip` because of a bug with pip locks that causes it to hang.

**Comment by fgrehm** [comment]
FTR - I made @SeMeKh a collaborator on this repository

**Comment by jvrplmlmn** [comment]
:+1: Great addition, can we get this in?

**Comment by SeMeKh** [comment]
I was just thinking of changing the actual cache directories so that we can make it forward-compatible. Will apply the change and merge it soon.

**Comment by SeMeKh** [comment]
Looks like there is no need to change the directory structure.

**Pull request merged**
