### PR TITLE
Add Slack Support

### PR DESCRIPTION
**Pull request by r1w1s1**
Hi @fgrehm @SeMeKh I just add the support for Slackware packages's system (slackpkg tool).

Cheers,
Ricardson

### CODE REVIEW

**Comment by SeMeKh** [comment]
Hi Ricardson
Thanks for your interest in `vagrant-cachier`.

Will you please rebase your code on top of our master? Other than that: LGTM.

**Comment by ricardson** [comment]
Hi @SeMeKh should be ok now.

**Comment by SeMeKh** [comment]
I don't think it is. Your code is removing the `pip` cache bucket. Do a `git pull` and then `git rebase origin/master`.

**Comment by ricardson** [comment]
looks ok now.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:

**Pull request closed without merging**
